apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: m6h8fuzuf-go 
  janus-idp.io/tekton: m6h8fuzuf-go
  backstage.io/kubernetes-id: m6h8fuzuf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m6h8fuzuf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml